- id: api
  name: api
  cmd:
    - pipenv run python api/app.py
- id: backend
  name: backend
  cmd:
    - pipenv run python backend/app.py
- id: frontend
  name: frontend
  cmd:
    - open frontend/index.html
- id: setup
  name: set up development environment
  cmd:
    - pipenv sync --dev
    - pipenv run pre-commit install
